# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bluedit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bluedit

  target 'BlueditTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BlueditUITests' do
    # Pods for testing
  end

end
